// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCreator creates a new instance of MockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreator {
	mock := &MockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCreator is an autogenerated mock type for the UserCreator type
type MockUserCreator struct {
	mock.Mock
}

type MockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreator) EXPECT() *MockUserCreator_Expecter {
	return &MockUserCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserCreator
func (_mock *MockUserCreator) Create(ctx context.Context, u User) (int, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) (int, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) int); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u User
func (_e *MockUserCreator_Expecter) Create(ctx interface{}, u interface{}) *MockUserCreator_Create_Call {
	return &MockUserCreator_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockUserCreator_Create_Call) Run(run func(ctx context.Context, u User)) *MockUserCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCreator_Create_Call) Return(n int, err error) *MockUserCreator_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserCreator_Create_Call) RunAndReturn(run func(ctx context.Context, u User) (int, error)) *MockUserCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// User provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) User(ctx context.Context, email string) (*User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockUserProvider_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) User(ctx interface{}, email interface{}) *MockUserProvider_User_Call {
	return &MockUserProvider_User_Call{Call: _e.mock.On("User", ctx, email)}
}

func (_c *MockUserProvider_User_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_User_Call) Return(user *User, err error) *MockUserProvider_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_User_Call) RunAndReturn(run func(ctx context.Context, email string) (*User, error)) *MockUserProvider_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventNotifier creates a new instance of MockEventNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventNotifier {
	mock := &MockEventNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventNotifier is an autogenerated mock type for the EventNotifier type
type MockEventNotifier struct {
	mock.Mock
}

type MockEventNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventNotifier) EXPECT() *MockEventNotifier_Expecter {
	return &MockEventNotifier_Expecter{mock: &_m.Mock}
}

// NotifyUserCreated provides a mock function for the type MockEventNotifier
func (_mock *MockEventNotifier) NotifyUserCreated(ctx context.Context, user User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventNotifier_NotifyUserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserCreated'
type MockEventNotifier_NotifyUserCreated_Call struct {
	*mock.Call
}

// NotifyUserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
func (_e *MockEventNotifier_Expecter) NotifyUserCreated(ctx interface{}, user interface{}) *MockEventNotifier_NotifyUserCreated_Call {
	return &MockEventNotifier_NotifyUserCreated_Call{Call: _e.mock.On("NotifyUserCreated", ctx, user)}
}

func (_c *MockEventNotifier_NotifyUserCreated_Call) Run(run func(ctx context.Context, user User)) *MockEventNotifier_NotifyUserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventNotifier_NotifyUserCreated_Call) Return(err error) *MockEventNotifier_NotifyUserCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventNotifier_NotifyUserCreated_Call) RunAndReturn(run func(ctx context.Context, user User) error) *MockEventNotifier_NotifyUserCreated_Call {
	_c.Call.Return(run)
	return _c
}
